### ISSUE TITLE
Command setup could be improved.

### ISSUE THREAD

**Issue by xuyuji9000** [coderbunker/aws-playground#2]
- use brew install awscli

- use brew install ebcli

**Comment by xuyuji9000** [comment]
need to update the process for ubuntu install `awscli` and `awsebcli`.

**Comment by veimis** [comment]
Raw notes:
Create AWS account atleast 24h prior to workshop (otherwise account verifocation may not have completed and eb create command fails)
 • Add instructions of adding a aws IMA user
 • Add information that you should use defaults on the eb interactive commands (init, create, deploy(?))
 • Terraform installation instructions

More ubuntu instructions
 • Docker installation
 • Set user as part of docker usergroup to avoid using sudo on each command
 • aws cli and aws eb cli installation

**Comment by xuyuji9000** [comment]
- Added IAM user with admin permission process
- added notification of docker ubuntu permission
